name: BUG Report
description: 'Create a BUG report to help me improve Pojav Zenith Horizon.'
title: "[BUG] Brief Description"
labels: [bug]
body:
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      options:
        - 'Game Issue'
        - 'Application Issue'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: |
        Clearly and in detail describe the issue you encountered.
    validations:
      required: true

  - type: textarea
    id: log
    attributes:
      label: Log File
      description: |
        Please upload the log file from the most recent occurrence of the issue here. This helps me quickly pinpoint the problem.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Videos
      description: |
        Upload screenshots or videos from the most recent occurrence of the issue. This may help me identify the problem faster.
    validations:
      required: false

  - type: textarea
    id: repetition
    attributes:
      label: Reproduction Steps
      description: |
        Steps to reproduce the issue. Please be as detailed as possible to help me quickly locate the problem.
      placeholder: |
        1. Open the launcher
        ... *(steps to reproduce the issue)*
      render: markdown
    validations:
      required: false

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: |
        A brief description of what you expected to happen.
    validations:
      required: false

  - type: dropdown
    id: android-version
    attributes:
      label: Android Version
      options:
        - '14'
        - '13'
        - '12'
        - '11'
        - '10'
        - '9'
        - '8'
        - '7-'
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: Pojav Zenith Horizon Version
      description: |
        Which version of Pojav Zenith Horizon did you encounter this issue in? You can check this on the "About Pojav Zenith Horizon" page.
      placeholder: 1.2.7
    validations:
      required: true

  - type: textarea
    id: more-info
    attributes:
      label: Additional Information
      description: |
        Provide more information to help me reproduce and fix the issue.
      value: |
        - Device Model:
        - CPU Architecture:
        - GPU Information:
      render: markdown
    validations:
      required: true

  - type: checkboxes
    id: check-issue
    attributes:
      label: This issue has not been reported before
      options:
        - label: I have checked the Issues and found no similar issue reported
          required: true
