name: BUG 反馈
description: '创建一个 BUG 反馈，帮助我改进 Pojav Zenith Horizon'
title: "[BUG] 简短的描述"
labels: [bug]
body:
  - type: dropdown
    id: issue-type
    attributes:
      label: 问题类型
      options:
        - '游戏问题'
        - '应用问题'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 问题描述
      description: |
        清晰，详细地描述出你所遇到的问题
    validations:
      required: true

  - type: textarea
    id: log
    attributes:
      label: 日志文件
      description: |
        你需要在这里上传最近一次遇到此问题的日志，直接帮助我快速定位问题
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: 截图或视频
      description: |
        上传最近一次遇到此问题的截图或者视频，可能会帮助我更快的确定问题
    validations:
      required: false

  - type: textarea
    id: repetition
    attributes:
      label: 复现步骤
      description: |
        复现问题的步骤，请尽量详细一些，方便我快速定位问题
      placeholder: |
        1. 打开启动器
        ... *(复现问题的一些操作)*
      render: markdown
    validations:
      required: false

  - type: textarea
    id: expected-behavior
    attributes:
      label: 预期行为
      description: |
        请对预期发生的情况的简明描述
    validations:
      required: false

  - type: dropdown
    id: android-version
    attributes:
      label: Android 版本
      options:
        - '14'
        - '13'
        - '12'
        - '11'
        - '10'
        - '9'
        - '8'
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: Pojav Zenith Horizon 版本
      description: |
        遇到此问题的版本是？你可以在“关于 Pojav Zenith Horizon”页面内查看
      placeholder: 1.2.6
    validations:
      required: true

  - type: textarea
    id: more-info
    attributes:
      label: 其他信息
      description: |
        提供更多信息，帮助我复现并修复问题
      value: |
        - 设备型号：
        - CPU 架构：
        - GPU 信息：
      render: markdown
    validations:
      required: true

  - type: checkboxes
    id: check-issue
    attributes:
      label: 这个问题还没有人反馈过
      options:
        - label: 我已经查看过 Issues，并且没有发现与之类似的问题被反馈
          required: true
